# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lcdnum_dist1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdnum_dist1.setObjectName("lcdnum_dist1")
        self.horizontalLayout_2.addWidget(self.lcdnum_dist1)
        self.lcdnum_dist3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdnum_dist3.setObjectName("lcdnum_dist3")
        self.horizontalLayout_2.addWidget(self.lcdnum_dist3)
        self.lcdnum_dist2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdnum_dist2.setObjectName("lcdnum_dist2")
        self.horizontalLayout_2.addWidget(self.lcdnum_dist2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lab_dist = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.lab_dist.setFont(font)
        self.lab_dist.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_dist.setObjectName("lab_dist")
        self.verticalLayout.addWidget(self.lab_dist)
        self.lcdnum_staticMeas = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdnum_staticMeas.setObjectName("lcdnum_staticMeas")
        self.verticalLayout.addWidget(self.lcdnum_staticMeas)
        self.lab_staticMeas = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.lab_staticMeas.setFont(font)
        self.lab_staticMeas.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_staticMeas.setObjectName("lab_staticMeas")
        self.verticalLayout.addWidget(self.lab_staticMeas)
        self.graphview_dynaMeas = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphview_dynaMeas.setObjectName("graphview_dynaMeas")
        self.verticalLayout.addWidget(self.graphview_dynaMeas)
        self.lab_dynaMeas = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.lab_dynaMeas.setFont(font)
        self.lab_dynaMeas.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_dynaMeas.setObjectName("lab_dynaMeas")
        self.verticalLayout.addWidget(self.lab_dynaMeas)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 10)
        self.verticalLayout.setStretch(5, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_portNum = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.lab_portNum.setFont(font)
        self.lab_portNum.setObjectName("lab_portNum")
        self.horizontalLayout.addWidget(self.lab_portNum)
        self.spinbox_portNum = QtWidgets.QSpinBox(self.tab)
        self.spinbox_portNum.setObjectName("spinbox_portNum")
        self.horizontalLayout.addWidget(self.spinbox_portNum)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.btn_open = QtWidgets.QPushButton(self.tab)
        self.btn_open.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btn_open.setFont(font)
        self.btn_open.setCheckable(False)
        self.btn_open.setObjectName("btn_open")
        self.verticalLayout_2.addWidget(self.btn_open)
        self.btn_close = QtWidgets.QPushButton(self.tab)
        self.btn_close.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btn_close.setFont(font)
        self.btn_close.setCheckable(False)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_2.addWidget(self.btn_close)
        self.btn_axis = QtWidgets.QPushButton(self.tab)
        self.btn_axis.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btn_axis.setFont(font)
        self.btn_axis.setObjectName("btn_axis")
        self.verticalLayout_2.addWidget(self.btn_axis)
        self.btn_zero = QtWidgets.QPushButton(self.tab)
        self.btn_zero.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btn_zero.setFont(font)
        self.btn_zero.setObjectName("btn_zero")
        self.verticalLayout_2.addWidget(self.btn_zero)
        self.btn_staticMeas = QtWidgets.QPushButton(self.tab)
        self.btn_staticMeas.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btn_staticMeas.setFont(font)
        self.btn_staticMeas.setObjectName("btn_staticMeas")
        self.verticalLayout_2.addWidget(self.btn_staticMeas)
        self.btn_dynaMeas = QtWidgets.QPushButton(self.tab)
        self.btn_dynaMeas.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btn_dynaMeas.setFont(font)
        self.btn_dynaMeas.setCheckable(True)
        self.btn_dynaMeas.setObjectName("btn_dynaMeas")
        self.verticalLayout_2.addWidget(self.btn_dynaMeas)
        self.btn_save = QtWidgets.QCheckBox(self.tab)
        self.btn_save.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_2.addWidget(self.btn_save)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.verticalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.setStretch(8, 5)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_3.setStretch(0, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_dist.setText(_translate("MainWindow", "激光器读数：距离/mm"))
        self.lab_staticMeas.setText(_translate("MainWindow", "静态测量结果：角度/°"))
        self.lab_dynaMeas.setText(_translate("MainWindow", "动态测量结果"))
        self.lab_portNum.setText(_translate("MainWindow", "端口号"))
        self.btn_open.setText(_translate("MainWindow", "连接设备"))
        self.btn_close.setText(_translate("MainWindow", "关闭设备"))
        self.btn_axis.setText(_translate("MainWindow", "旋转轴标定"))
        self.btn_zero.setText(_translate("MainWindow", "零位确定"))
        self.btn_staticMeas.setText(_translate("MainWindow", "静态测量"))
        self.btn_dynaMeas.setText(_translate("MainWindow", "动态测量"))
        self.btn_save.setText(_translate("MainWindow", "保存至文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "控制"))
